# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  arm_arm2_joint:
    has_velocity_limits: false
    max_velocity: 4
    has_acceleration_limits: false
    max_acceleration: 5
  arm2_arm3_joint:
    has_velocity_limits: false
    max_velocity: 4
    has_acceleration_limits: false
    max_acceleration: 5
  arm3_end_effector_joint:
    has_velocity_limits: false
    max_velocity: 4
    has_acceleration_limits: false
    max_acceleration: 5
  shoulder_arm_joint:
    has_velocity_limits: false
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 5
  shoulder_base_joint:
    has_velocity_limits: false
    max_velocity: 4
    has_acceleration_limits: false
    max_acceleration: 6
