ur5_robot_manipulator:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: shoulder_base_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: shoulder_arm_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: arm_arm2_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: arm2_arm3_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: arm3_end_effector_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
